---
name: "Last.fm (Bananz0)"
guid: "f5cc9733-e4df-42f3-a950-12d62d5819cc"
version: "12.0.0.11"
targetAbi: "12.0.0.0"
framework: "net10.0"
overview: "A plugin that scrobbles your Jellyfin music to Last.fm"
description: >
  Scrobble Last.fm plays with Jellyfin.
category: "Music"
owner: "Bananz0"
artifacts:
  - "Jellyfin.Plugin.Lastfm.dll"
changelog: >
  Manifest tools updated to danielfariati/jellyfin-utilities
